API/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from rest_framework.routers import DefaultRouter
from .web_api_views import *
from .android_api_views import *

  
urlpatterns = [
    path('login', login, name='api_login'), 
    path('get_vehicle_details', get_vehicle_details, name='api_get_vehicle_details'), 

    path('allocate_driver_to_vehicle', allocate_driver_to_vehicle, name='api_allocate_driver_to_vehicle'), 
    path('leave_driver_from_vehicle', leave_driver_from_vehicle, name='api_leave_driver_from_vehicle'), 

    path('get_breakdown_type', get_breakdown_type, name='api_get_breakdown_type'), 
    path('create_breakdown', create_breakdown, name='api_create_breakdown'), 

    path('get_driver_allocation_history', get_driver_allocation_history, name='api_get_driver_allocation_history'), 

    path('get_vehicle_or_fuel_details', get_vehicle_or_fuel_details, name='api_get_vehicle_or_fuel_details'), 
    path('create_fuel_record', create_fuel_record, name='api_create_fuel_record'), 
    path('get_last_fuel_record', get_last_fuel_record, name='api_get_last_fuel_record'), 
    path('get_fuel_history', get_fuel_history, name='api_get_fuel_history'), 
  

    # WEB APIS
    path('allocations_web', allocate_driver_list_create, name='allocate-driver-list-create-web'),
    path('allocations_web/<int:pk>', allocate_driver_detail, name='allocate-driver-detail-web'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ERP_Workshop/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('dashboard/', views.dashboard, name='workshop_dashboard'),
    path('breakdown_list/', views.breakdown_list, name='workshop_breakdown_list'),
    path('update_breakdown_status/<int:id>', views.update_breakdown_status, name='workshop_update_breakdown_status'),
    path('delete_breakdown/<int:id>', views.delete_breakdown, name='workshop_delete_breakdown'),
    path('get_breakdown_details/', views.get_breakdown_details, name='workshop_get_breakdown_details'),
 
    path('job_card_list/', views.job_card_list, name='workshop_job_card_list'),
    path('create_job_card/', views.create_job_card, name='workshop_create_job_card'),
    path('update_job_card/<int:id>', views.update_job_card, name='workshop_update_job_card'),
    path('delete_job_card/<int:id>', views.delete_job_card, name='workshop_delete_job_card'),
    path('job_card_item_list/<int:id>', views.job_card_item_list, name='workshop_job_card_item_list'),
    path('delete_job_card_item/<int:id>', views.delete_job_card_item, name='workshop_delete_job_card_item'),
    path('close_job_card/', views.close_job_card, name='workshop_close_job_card'),
    path('print_job_card/<int:id>', views.print_job_card, name='workshop_print_job_card'),

    path('maintenance-logs/', views.maintenance_logs, name='workshop_maintenance_logs'),
    path('maintenance-schedule/', views.maintenance_schedule, name='workshop_maintenance_schedule'),

    path('product-list/', views.product_list, name='workshop_product_list'),
    path('create-product/', views.create_product, name='workshop_create_product'),
    path('update_product/<int:id>', views.update_product, name='workshop_update_product'),
    path('import-product/', views.import_products, name='workshop_import_products'),
    path('delete-product/<int:id>', views.delete_product, name='workshop_delete_product'),

    path('purchase-list/', views.purchase_list, name='workshop_purchase_list'),
    path('create-purchase/', views.create_purchase, name='workshop_create_purchase'),
    path('update_purchase/<int:id>', views.update_purchase, name='workshop_update_purchase'),
    path('delete-purchase/<int:id>', views.delete_purchase, name='workshop_delete_purchase'),

    path('get_product_details/', views.get_product_details, name='workshop_get_product_details'),
    path('delete_purchase_item/<int:id>', views.delete_purchase_item, name='workshop_delete_purchase_item'),
    path('purchase-item-list/<int:id>', views.purchase_item_list, name='workshop_purchase_item_list'),

    path('reports/', views.reports, name='workshop_reports'),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SLD/urls.py
from django.contrib import admin
from django.urls import path,include
from Website import views as WebView 
from Website import urls as WebUrls
from ERP_Admin import urls as ERP_Admin_Urls 
from API import web_urls as APIWebUrls
from API import android_urls as APIAndroidUrls
from ERP_Account import urls as ERP_Account_Urls
from ERP_Workshop import urls as ERP_Workshop_Urls
from ERP_Finance import urls as ERP_Finance_Urls
from ERP_Admin import views as ERP_Admin_View
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    
    path('default-admin/', admin.site.urls),
    path('', WebView.index, name="index"), 
    path('admin/', include(ERP_Admin_Urls)),  
    path('account/', include(ERP_Account_Urls)),  
    path('workshop/', include(ERP_Workshop_Urls)),
    path('finance/', include(ERP_Finance_Urls)),
    path('login/', ERP_Admin_View.login, name="login"), 
    path('logout/', ERP_Admin_View.logout, name="logout"),  
    path('delete_user/<int:id>', ERP_Admin_View.delete_user, name="delete_user"),  
    path('web/', include(WebUrls)),
    path('api/android/', include(APIAndroidUrls)),
    path('api/web/', include(APIWebUrls)),


]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]

ERP_Admin/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models, transaction
import os

from django.conf import settings

class EMP_ID(models.Model):
    emp_id = models.CharField(max_length=20) 
    def __str__(self):
        return f"{self.emp_id}"

class CustomUser(AbstractUser):
    is_admin = models.BooleanField(default=False)
    is_account = models.BooleanField(default=False)
    is_workshop = models.BooleanField(default=False)
    is_driver = models.BooleanField(default=False)
    is_finance = models.BooleanField(default=False)
    is_fuel = models.BooleanField(default=False) 
    emp_id = models.OneToOneField(EMP_ID, on_delete=models.CASCADE, null=True)
    profile_photo=models.ImageField(upload_to="profile_images", max_length=None, null=True, blank=True)
    groups = models.ManyToManyField(
        Group,
        related_name='customuser_groups',  # Custom reverse relation name
        blank=True
    )
    user_permissions = models.ManyToManyField(
        Permission,
        related_name='customuser_permissions',  # Custom reverse relation name
        blank=True
    )
     
    def __str__(self):
        return self.username


 
class VehicleModel(models.Model):
    model_name = models.CharField(max_length=50, unique=True, db_index=True) 
    def __str__(self):
        return self.model_name
 
class Insurance_Bank(models.Model):
    bank_name = models.CharField(max_length=50, unique=True, db_index=True) 
    def __str__(self):
        return self.bank_name
 
class Finance_Bank(models.Model):
    bank_name = models.CharField(max_length=50, unique=True, db_index=True) 
    def __str__(self):
        return self.bank_name
 
class PolicyInsurance_Company(models.Model):
    name = models.CharField(max_length=50, unique=True, db_index=True) 
    def __str__(self):
        return self.name


VEHICLE_STATUS = (
    ('active', 'active'),
    ('inactive', 'Inactive'), 
) 



class Vehicle(models.Model):
    owner_name = models.CharField(max_length=50,null=True,blank=True)
    model_name = models.ForeignKey(VehicleModel, related_name='vehicle_model_name', null=True, blank=True, on_delete=models.CASCADE)
    vehicle_number = models.CharField(max_length=50, unique=True)
    status=models.CharField(max_length=50, default='active', choices=VEHICLE_STATUS)
    def __str__(self):
        return f"{self.model_name.model_name} ({self.vehicle_number[:-5]} {self.vehicle_number[-4:]})"


class Driver(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True)
    driver_name = models.CharField(max_length=20, null=False, blank=False)
    license_number = models.CharField(max_length=20, unique=True, null=True, blank=True)
    adhaar_number = models.CharField(max_length=20, unique=True, null=True, blank=True)
    mobile_number = models.CharField(max_length=15, null=True, blank=True)
    alternate_mobile_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.TextField(null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    date_joined = models.DateField(auto_now_add=False, null=True, blank=True)
    adhaar_card_photo=models.FileField(upload_to="Documents", max_length=None, null=True, blank=True)
    pan_card_photo=models.FileField(upload_to="Documents", max_length=None, null=True, blank=True)
    driving_license_photo=models.FileField(upload_to="Documents", max_length=None, null=True, blank=True)
    profile_photo=models.ImageField(upload_to="Documents", max_length=None, null=True, blank=True)
    
    def __str__(self):
        return f"{self.driver_name} - {self.user.username}"
    


class Technician(models.Model):
    emp_id = models.ForeignKey(EMP_ID, on_delete=models.CASCADE, null=True)
    technician_name = models.CharField(max_length=100, verbose_name="Technician Name")
    adhaar_number = models.CharField(max_length=20, unique=True, verbose_name="Aadhaar Number")
    mobile_number = models.CharField(max_length=10, unique=True, verbose_name="Mobile Number")
    alternate_mobile_number = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(max_length=100, unique=True, null=True, blank=True, verbose_name="Email Address")
    address = models.TextField(null=True, blank=True, verbose_name="Address")
    date_of_birth = models.DateField(null=True, blank=True, verbose_name="Date of Birth")
    date_joined = models.DateField(auto_now_add=True, verbose_name="Date Joined") 
    pan_card=models.FileField(upload_to="Documents", max_length=None, null=True, blank=True)
    adhaar_card=models.FileField(upload_to="Documents", max_length=None, null=True, blank=True)
    profile_photo=models.FileField(upload_to="Documents", max_length=None, null=True, blank=True)
    additional_docs=models.FileField(upload_to="Documents", max_length=None, null=True, blank=True)

    
    def save(self, *args, **kwargs):
        if not self.id:  # Only execute this logic when creating a new driver instance
            last_emp_id = EMP_ID.objects.order_by('-id').first()
            if last_emp_id:
                last_number = int(last_emp_id.emp_id.split('-')[1])
                # Create a new EMP_ID instance or fetch it if necessary
                new_emp_id = EMP_ID.objects.create(emp_id=f"SLD-{last_number + 1}")
                self.emp_id = new_emp_id  # Assign the EMP_ID instance to emp_id
            else:
                # Create the first EMP_ID instance
                new_emp_id = EMP_ID.objects.create(emp_id="SLD-1")
                self.emp_id = new_emp_id  # Assign the EMP_ID instance to emp_id
        super().save(*args, **kwargs)


    def __str__(self):
        return f"{self.technician_name}"

    class Meta:
        verbose_name = "Technician"
        verbose_name_plural = "Technicians"


class Party(models.Model):
    business_name = models.CharField(max_length=100)
    customer_name = models.CharField(max_length=100)
    gst_number = models.CharField(max_length=15, unique=True, blank=True, null=True)
    mobile_number = models.CharField(max_length=15, unique=True)
    alternate_mobile_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.TextField(null=True, blank=True, verbose_name="Address")
    document1=models.FileField(upload_to="ClientDocuments", max_length=None, null=True, blank=True)
    document2=models.FileField(upload_to="ClientDocuments", max_length=None, null=True, blank=True)
    document3=models.FileField(upload_to="ClientDocuments", max_length=None, null=True, blank=True)

    def __str__(self):
        return self.business_name
    



class Product(models.Model):
    product_code = models.CharField(max_length=20, unique=True, db_index=True)
    product_name = models.CharField(max_length=100, db_index=True)
    model = models.ForeignKey(VehicleModel, related_name='items', null=True, blank=True, on_delete=models.CASCADE)
    description = models.TextField(null=True, blank=True)
    sale_price = models.DecimalField(max_digits=10, decimal_places=2, null=True)  # Use DecimalField for monetary values
    minimum_stock_alert = models.PositiveIntegerField(default=0)
    available_stock = models.IntegerField(default=0, db_index=True, null=True, blank=True)
    product_image=models.ImageField(upload_to="Product Images", height_field=None, width_field=None, max_length=500, null=True, blank=True)
 
    def __str__(self):
        return f" #{self.product_code} on {self.product_name}"

PURCHASE_GST=(
    ('GST BILL','GST BILL'),
    ('Without GST BILL','Without GST BILL')
)

PURCHASE_PAID_STATUS=(
    ('Paid','Paid'),
    ('UnPaid','UnPaid')
)
class Purchase(models.Model):
    bill_no = models.CharField(max_length=50, db_index=True, unique=True, null=False, blank=False)
    supplier_name = models.CharField(max_length=100, db_index=True, null=True, blank=True)
    bill_type = models.CharField(max_length=30, db_index=True, choices=PURCHASE_GST)
    bill_date = models.DateField(auto_now_add=False, db_index=True)
    total_cost = models.DecimalField(max_digits=12, decimal_places=2, default=0.0)
    bill_file = models.FileField(upload_to="Purchase Bill", null=True, blank=False)
    paid_status = models.CharField(max_length=20, choices=PURCHASE_PAID_STATUS, default='UnPaid')
    def __str__(self):
        return f"Purchase #{self.bill_no} on {self.bill_date}"


class PurchaseItem(models.Model):
    purchase = models.ForeignKey(Purchase, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, db_index=True)
    quantity = models.PositiveIntegerField()
    cost_per_unit = models.DecimalField(max_digits=10, decimal_places=2)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def save(self, *args, **kwargs):
        # Update product stock on save
        if self.pk is None:  # Only add stock if it's a new record
            self.product.available_stock += self.quantity
        else:  # If updated, adjust stock accordingly
            original = PurchaseItem.objects.get(pk=self.pk)
            self.product.available_stock += self.quantity - original.quantity
        self.product.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Adjust stock on deletion
        self.product.available_stock -= self.quantity
        self.product.save()
        super().delete(*args, **kwargs)

    def __str__(self):
        return f"{self.quantity} of {self.product.product_name} in Purchase #{self.purchase.id}"


from django.db import models
from django.core.validators import MinValueValidator

JOB_CARD_STATUS = [
    ('pending', 'Pending'),
    ('in_progress', 'In Progress'),
    ('completed', 'Completed'),
]


class JobCard(models.Model):

ERP_Workshop/templates/workshop_job_card_management.html
{% extends "workshop_base.html" %}
{% block title %}Job Card Management{% endblock title %}
{% block content %}
<style>
 
</style>
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Job Card Management</h1>
        <div class="row">
            <div class="col">
            </div>
        </div>
    </div><!-- End Page Title -->
   
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-sm-12"> <br><br>
                 
                
                 

            </div>
        </div>
    </div>
</main><!-- End #main -->
 
{% endblock content %}

ERP_Workshop/templates/workshop_maintenance_logs.html
{% extends "workshop_base.html" %}
{% block title %}Maintenance Logs{% endblock title %}
{% block content %}
<style>
 
</style>
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Maintenance Logs</h1>
        <div class="row">
            <div class="col">
            </div>
        </div>
    </div><!-- End Page Title -->
   
    <div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-sm-12"> <br><br>
                 
                
                 

            </div>
        </div>
    </div>
</main><!-- End #main -->
 
{% endblock content %}

ERP_Workshop/templates/workshop_purchase_item_list.html
{% extends "base_window.html" %}
{% block title %}Purchase Item{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 100px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 1;
        border-radius: 10px;
    }

    .dropdown-content a {
        color: black;
        padding: 5px 10px;
        text-decoration: none;
        display: block;
        text-align: left;
    }

    .dropdown-content a:hover {
        background-color: #f1f1f1;
    }

    .dropdown:hover .dropdown-content {
        display: block;
    }



    .bill-info-header {
        background-color: #f9f9f9;
        border-radius: 12px;
        box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin-top: 20px;
    }

    .info-field {
        background-color: #f1f1f1;
        padding: 15px;
        border-radius: 8px;
        border: 1px solid #ddd;
        font-size: 1rem;
        color: #555;
        width: 100%;
        text-align: left;
    }

    .info-field strong {
        color: #333;
        margin-bottom: 5px;
    }

    .col-sm-3 {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .col-sm-4 {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    @media (max-width: 768px) {

        .col-sm-3,
        .col-sm-4 {
            margin-bottom: 15px;
        }
    }


    .form-header {
        background-color: #f9f9f9;
        border-radius: 12px;
        box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin-top: 20px;
    }
</style>
<main id="main" class="main">


    <section class="section dashboard">
        <div class="alert alert-warning text-center mt-2 p-1">
            <h2>Purchase Items </h2>
        </div>  
         
        <div class="container-fluid mb-3 bill-info-header">
            <div class="row">
                <!-- Bill No -->
                <div class="col-sm-4 mb-2">
                    <div class="info-field">
                        <strong>Bill No:</strong> {{ purchase.bill_no }}
                    </div>
                </div>

                <!-- Supplier Name -->
                <div class="col-sm-4 mb-2">
                    <div class="info-field">
                        <strong>Supplier Name:</strong> {{ purchase.supplier_name }}
                    </div>
                </div>

                <!-- Bill Type -->
                <div class="col-sm-4 mb-2">
                    <div class="info-field">
                        <strong>Bill Type:</strong> {{ purchase.bill_type }}
                    </div>
                </div>

                <!-- Bill Date -->
                <div class="col-sm-3 mb-2">
                    <div class="info-field">
                        <strong>Bill Date:</strong> {{ purchase.bill_date }}
                    </div>
                </div>

                <!-- Total Cost -->
                <div class="col-sm-3 mb-2">
                    <div class="info-field">
                        <strong>Total Cost:</strong> {{ purchase.total_cost }}
                    </div>
                </div>

                <!-- Total Cost -->
                <div class="col-sm-3 mb-2">
                    <div class="info-field">
                        <strong>Payment Status:</strong>  
                        {% if purchase.paid_status == "Paid" %}
                        <span class="badge bg-success">Paid</span>
                        {% else %}
                            <span class="badge bg-danger">Un Paid</span>
                        {% endif %}
                    </div>
                </div>

                <!-- Total Cost -->
                <div class="col-sm-3 mb-2">
                    <div class="info-field">
                        {% if purchase.bill_file %}
                        <a href="{{purchase.bill_file.url}}" class="btn btn-success" download>Download Biil</a>
                        {% else %}
                        <a href="" class="btn btn-secondary" >Bill Not Available</a>
                        {% endif %}

                        
                    </div>
                </div>
                <!-- Bill File -->

            </div>
        </div>

        <div class="container-fluid mb-3 form-header">
            <div class="row">
                <div class="col-sm-9">

                    <form action="#" method="get" class="position-relative">{% csrf_token %}
                        <select name="search_product" id="search_product" class="form-control" onchange="get_details()" required>
                            <option value="">Search Product...</option>
                            {% for r in product_data %}
                            <option value="{{ r.product_code }}">{{ r.product_name }}</option>
                            {% endfor %}
                        </select> 
                    </form>
                     
                   <form method="POST"> {% csrf_token %} 
                        <div class="row  mt-1">
                            <div class="col-md-2">
                                <input type="text" class="form-control" id="id_product_code" name="product_code" placeholder="Product Code" readonly />
                            </div>
                            <div class="col-md-4">
                                <input type="text" class="form-control" id="id_product_name" name="product_name" placeholder="Product Name" readonly />
                            </div>
                            <div class="col-md-2">
                                {{ form.quantity|as_crispy_field }}
                            </div>
                            <div class="col-md-2">
                                {{ form.cost_per_unit|as_crispy_field }}
                            </div>
                            <div class="col-md-2">
                                {{ form.total_amount|as_crispy_field }}
                            </div>
                        </div>
                        
                        <input type="hidden" class="form-control" id="product_id" name="product_id" required />
                        
                        <center><button type="submit" class="btn btn-primary mt-1 px-5">Submit</button></center>
                    </form>

                </div> 
                <div class="col-sm-3">
                    <img src="" alt="" name="product_image" id="product_image" style=" width: 150px; height: 150px;">
                </div>

            </div>
        </div>

        <div class="container mt-3" style=" overflow:scroll;">
            <table id="example" class="table table-striped "
                style="overflow:scroll; width:100%;min-width: max-content;">
                <thead class="bg-danger">
                    <tr class="bg-gradient-primary text-light ">
                        <th scope="col" class="text-center text-white" style="">Sr.No</th>
                        <th scope="col" class="text-center text-white" style="">Product Code</th>
                        <th scope="col" class="text-center text-white" style="">Product Name</th>
                        <th scope="col" class="text-center text-white" style="">Quantity</th>
                        <th scope="col" class="text-center text-white" style="">Rate</th>
                        <th scope="col" class="text-center text-white" style="">Total Amount</th>
                        <th scope="col" class="text-center text-white" style="">Action</th>
                    </tr>
                </thead>
                <tbody id="purchase_table_body">
                    {% if item %}
                    {% for r in item %}
                    <tr>
                        <td class="text-center">{{forloop.counter}}</td>
                        <td>{{r.product.product_code}}</td>
                        <td class="text-center">{{r.product.product_name}}</td>
                        <td class="text-center">{{r.quantity}}</td>
                        <td class="text-center">{{r.cost_per_unit}}</td>
                        <td class="text-center">&#8377; {{r.total_amount}}</td>
                        <td>
                            <center>
                                <a href="{% url 'workshop_delete_purchase_item' r.id %}" class="btn btn-danger px-3">Delete</a>
                            </center>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td></td>
                        <td></td>
                        <td class="text-center"></td>
                        <td class="text-center"></td>
                        <td class="text-center"><b>Total</b></td>
                        <td class="text-center"><b>&#8377; {{total_amount}}</b></td>
                        <td> </td>
                    </tr>
                    {% else %}

                    {% endif %}
                </tbody>
            </table>
        </div>
    </section>

</main><!-- End #main -->


<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
 

<script>
    function get_details() {
        var productCode = $('#search_product').val(); // Obtain the selected product code

        if (productCode) {
            $.ajax({
                url: '/workshop/get_product_details/',  // Update with your actual endpoint
                data: { 'product_code': productCode },
                type: 'GET',
                success: function(data) {
                    if (!data.error) {
                        // Populate form fields with product details
                        $('#id_product_code').val(data.product_code);
                        $('#id_product_name').val(data.product_name);
                        $('#id_cost_per_unit').val(data.product_rate);
                        $('#id_total_amount').val(data.product_rate);
                        $('#product_id').val(data.id);
                        $('#id_quantity').val(1);
                        if (data.product_image_url) {
                            $('#product_image').attr('src', data.product_image_url);  // Set the image URL dynamically
                        } else {
                            $('#product_image').attr('src', 'default-image.jpg');  // Set a default image if not available
                        }
                        // var qty = $('#id_quantity').val(1);  // Default quantity
                        // var rate = parseFloat(data.sale_amount);
                        

                    } else {
                        console.error(data.error);
                    }
                },
                error: function(error) {
                    console.error('Error fetching product details:', error);
                    alert('Failed to fetch product details. Please try again.');
                }
            });
        } else {
            alert('Please select a valid product.');
        }
    }



    function calculate_amount(){
        var qty = $('#id_quantity').val();
        var rate = $('#id_cost_per_unit').val();
        $('#id_total_amount').val(qty*rate);
    }
</script>

 

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const element = document.getElementById('search_product');
        const choices = new Choices(element, {
            searchEnabled: true,
            itemSelectText: '',
            noResultsText: 'No matching results',
        });
    });
</script>

{% endblock content %}

ERP_Workshop/templates/workshop_update_product.html
{% extends "base_window.html" %}
{% block title %}Update Product{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<style> 
     #reported_defect{
        height:10px;
     }
</style>
<main id="main" class="main">

    
    <section class="section dashboard">
        <div class="alert alert-warning text-center mt-2 p-1">
            <h2>Update Product</h2>
        </div>  

        <div class="container-fluid mb-3 form-header p-3">
            <div class="row p-1 rounded">
                <div class="col-sm-12">
                     
                     
                   <form method="POST" enctype="multipart/form-data" > {% csrf_token %} 
                    <div class="row">
                        <div class="col-sm-6">
                           {{ form.product_code|as_crispy_field }}
                       </div>
                       <div class="col-sm-6"> 
                           <label for="id_model" class="mb-2">Model</label>
                           {{ form.model }}
                       </div>
                       <div class="col-sm-12">
                           {{ form.product_name|as_crispy_field }}
                       </div>
                       <div class="col-sm-12">
                           {{ form.description|as_crispy_field }}
                       </div>
                       <div class="col-sm-6">
                           {{ form.sale_price|as_crispy_field }}
                       </div>
                       <div class="col-sm-6">
                           {{ form.minimum_stock_alert|as_crispy_field }}
                       </div>
                       <div class="col-sm-6">
                           {{ form.available_stock|as_crispy_field }}
                       </div>
                       <div class="col-sm-6">
                           {{ form.product_image|as_crispy_field }}
                       </div> 
                   </div>

                        <center><button type="submit" class="btn btn-primary mt-1 px-5">Submit</button></center>
                    </form>

                </div>  
            </div>
        </div>

         
    </section>

</main><!-- End #main -->

 
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const dropdownIds = ['id_model',];
        dropdownIds.forEach(id => {
            const element = document.getElementById(id);
            if (element) {
                new Choices(element, {
                    searchEnabled: true,
                    itemSelectText: '',
                    noResultsText: 'No matching results',
                });
            }
        });
    });
</script>
{% endblock content %}